<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>

<?php
/** @var YAV_Bansale_Helper_Data $bansaleHelper */
$bansaleHelper = Mage::helper('bansale');
?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if (!$_product->isGrouped()): ?>
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <input type="text" name="qty" id="qty" maxlength="12"
                   value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>"
                   class="input-text qty"/>
        <?php endif; ?>
        <?php
        $disabled = '';
        if ($bansaleHelper->checkAvailabilityProduct($_product)) {
            $disabled = 'disabled';
        }
        ?>
        <button <?php echo $disabled ?> type="button" title="<?php echo $buttonTitle ?>"
                                        id="product-addtocart-button"
                                        class="button btn-cart"
                                        onclick="productAddToCartForm.submit(this)">
            <span><span><?php echo $buttonTitle ?></span></span>
        </button>
        <?php if ($disabled): ?>
            <span class="error"><?php echo 'The sale is temporarily suspended.' ?></span>
        <?php endif; ?>
    </div>
<?php endif; ?>

